# main text of home
name: Mahesh Dananjaya

bio: <p>I am a masters student in computer science at the University of Edinburgh. I am broadly interested in computer architecture and distributed systems with particular emphasis on memory consistency models, coherence protocols and persistent memory.

#systems and programming/compiler support for parallel architectures, memory systems and distributed computing systems with particular emphasis on memory consistency, coherence protocols and memory persistency (non-volatile memory)</p>. Please find more information below!. Thank you.

#I am affiliated to Compilers and Architecture Design (CArD) research group of Institute of Computing Systems Architecture (ICSA) at School of Informatics. I am also a student of Centre for Doctoral Training (CDT) in Pervasive Parallelism. I am working on architecture and programming/compiler support for parallel computing, memory systems and distributed systems with particular emphasis on memory consistency, cache coherency and memory persistency</p>
#Gradute Student in Computer Science at University of Edinburgh

#<div><section><p>I am a graduate student in computer science at <a style="text-decoration:none" href="https://www.ed.ac.uk/">University of Edinburgh</a> . I am affiliated to Compiler and Architecture Design - <a style="text-decoration:none" href="http://www.icsa.informatics.ed.ac.uk/compilers/">CArD</a> group of Institute of Computing Systems Architecture (ICSA) at School of Informatics. I am also a student at EPSRC Center for Doctoral Training (CDT) in Pervasive Parallelism.</p></section></div>


#<section><p>I am a graduate student in computer science at <a style="text-decoration:none" href="https://www.ed.ac.uk/">University of Edinburgh</a> . I am affiliated to Compiler and Architecture Design - <a style="text-decoration:none" href="http://www.icsa.informatics.ed.ac.uk/compilers/">CArD</a> group of Institute of Computing Systems Architecture - <a style="text-decoration:none" href="http://web.inf.ed.ac.uk/icsa/">ICSA</a> at School of Informatics. I am also a student of EPSRC Centre for Doctoral Training (CDT) in <a style="text-decoration:none" href="http://web.inf.ed.ac.uk/infweb/student-services/cdt/pervasive-parallelism">Pervasive Parallelism</a>.</p></section>
#![Profile Image]({{ site.url }}/{{ site.picture }})
# "assets/images/logoed.png"

#![Profile Image]({{ site.url }}/{{ site.cover }})

#<p class="extra"> <a class="link" href="https://github.com/sergiokopplin/indigo">Indigo theme</a> by <a class="link" href="https://github.com/sergiokopplin/indigo">Kopplin</a></p>

#Nav
#{% if site.resume == true %}             <li class="item">                 <a class="link" href="{% if site.resume-external %}{{ site.resume-url }}{% else %}{{ site.url }}/{{ site.resume-url }}{% endif %}">Résumé</a>             </li>        {% endif %}

#   or page.title == "Blog"
#   or page.title == "Projects"

# twitter summary info
description: Mahesh Dananjaya's Personal Web Site

# if it's an external image, update below for true
# better with square images
external-image: false
#picture: assets/images/profile.jpg
#picture: assets/images/mahesh2.jpg
picture: assets/images/mahesh3.jpg

cover: assets/images/edincover1.jpg

footerpic: assets/images/logoed.png
footerpic2: assets/images/complogo.png
footerpic3: assets/images/pparlogo.jpg
footerpic4: assets/images/icsalogo.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
#resume: true
resume: true
resume-external: true
resume-url: https://google.com/?q=my+resume

#url: https://koppl.in/indigo
url: https://maheshdananjaya.github.io
# your url: http://USERNAME.github.io
port: 4001
permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: dananjaya.mahesh.9
#twitter: mahesh91uom
# google: mygoogle
#instagram: mahesh.dananjaya
# pinterest: mypinterest
linkedin: dananjayamahesh
# youtube: myyoutube
# spotify: myspotify
github: dananjayamahesh
# gitlab: mygitlab
# lastfm: mylastfm
stackoverflow: 9152362/mahesh-dananjaya
quora: Mahesh-Dananjaya
# reddit: username
#medium: dananjayamahesh
# vimeo: myvimeo
# lanyrd: mylanyrd
email: mahesh.dananjaya@ed.ac.uk

authors:
    johndoe:
        name: Mahesh Dananjaya
        bio: Grad Student in Computer Science
        external-image: false
        picture: assets/images/mahesh2.jpg
        twitter: mahesh91uom
    

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
#width: normal
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false
publications: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
